---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elasticsearch-master-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBzFR4f6wm5io7GMZIdFm/23ixU1SsQfAfQn7IHgGcsuQ+2bnFRFOKU5KA9GycXzdNjWhbGpRKDAKYgRdqsY+ifp8dx6OQgPjMKupJBdREPfYg7J6DfTCCyHAuuNtU7Jp8yomy2WqDh0kN1O1b2CCNmHkMODpGzpwSPYD6DRLfUcoj4xUspNcv8IiSm2z/cDFeSGzEEUN+l+kPFwtq4fuZ0yD3HAcBT6Sh8XDQImKq8UVNFzgVY2NopJoDQ7yz0IeO2osz+VVKNgq63Tce+IgSVCyZ4dLMyYa3wgtgxyipckvvkyKpsieHaCWf410fkzVMTqp4PYUJQPVyy5ogV6/Up+1MBdUfW3KiCuqdhAwOuC2J2UBC+RfApV0QGOMQcrITapzZccNhq24lwg5PjG0DlSDe0X0aFEpN1Ct7Vbeps7sJUoyy4HkOs/fV/H/EHHjwsi2K1fyQZht7Vxt5iFIqM84jBNjZR4+TAngyhhJ5mmAHPZi5vkim3ikQ0vcE1Ts9H8TY8GHuMea4Otye1sj74OiabJUhCl2rKtXAz/4A6DH/b1olBGfhTDXQBTqnSSjAyDyvYsJ7HYozzAXJqxEhsBYBbq7MbCfLv6aX7rxsFq7pynr933UI2m0/nwRPf9sH2yG1htIQtFZt2F0vjvTysH000jRHwCC/UTgkVWENoBlg752zLk91T3f78vwMhZkzCxOWhQa5W34Rd
  template:
    metadata:
      creationTimestamp: null
      name: elasticsearch-master-credentials
      namespace: default
