---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluentd
  namespace: fluentd
spec:
  encryptedData:
    password: AgDM3T4eZ5QyYndvPQQWoxkbm11o7P9a8SLlS56zlo62njvsTaiCYKg7fj6VQt03VTzEe+3MSSbzfGVDEbcx+bDcfgKEeya1G8UnmDuBrY+/HMNyjUwJe+BW88wnPaJUog43JzhaEubymghpGJ76eB+RX6rVIhA9hUZx4BSh0jdYejXKWY+NsRPPrVoBbayGRxINDiHtWOJOs3kG0lvx4jxLfdKQRZKlNDq2dbflYZpIbDk+cY3FKEIO7tuyYJuPDroVPOHg/uKnLKqR5XyYnjft07/LJk6UUacrCiyQaxKIwCrYJBmx+m1q6ylh9DeEyKFAtI1OnC4p12aqimbh7ALFq+lHkidya+ycUHQIVglr8rF329TOTWGHEGoDy9l/VJgeZSvCJWRp6r5izcBynS91wWiID5rYfeGZm0bzJnNFEupL8wCHTb/evu6HplzNf8aIPvZl329bNvWwgcNrxX8aOWRbpLuv7/5qidJmtjtqS6i4Oa1sflxTFOO596Li/JeAMyRSdaMJzraSlhMsxz/uIkRhELbcHjiOSUSeK0ucQQjslacFJ3zMDzH7mAtx/UAfxC1x4LCa2tOSw8CzOHU9HyIziMGbwXnF2R15loQNzw2KOk18Fj8U3AaZhX2IiQAMHB6zc6aNgXoDbbkLfoNDeaegOUIzCXWu3EQA8w0pP0FIwDj95Hqqn2Jg4WqlRtuZC1oCPvR19kRM
  template:
    metadata:
      creationTimestamp: null
      name: fluentd
      namespace: fluentd
