apiVersion: v1
data:
  DYNAMO_TBL: cHJlZGljdGlvbnMtdGFibGUtdGVycmFmb3JtLXByb2Q=
  GPT_TBL: b3BlbmFpLXRhYmxlLXRlcnJhZm9ybS1wcm9k
  REGION_NAME: YXAtbm9ydGhlYXN0LTE=
  SNS_ARN: YXJuOmF3czpzbnM6YXAtbm9ydGhlYXN0LTE6OTMzMDYwODM4NzUyOnRlbGVncmFtYm90LXlvbG92NS1zbnMtcHJvZA==
  SNS_URL: dGVsZWdyYW1ib3QteW9sb3Y1LXNucy1wcm9k
  SQS_URL: dGVsZWdyYW1ib3QteW9sb3Y1LXNxcy1wcm9k
  TELEGRAM_TOKEN: NzExNDkwMTYwMzpBQUdqTWQ0ZlY5aEc1YU1hWUZTd1dmNHZFSzByNlpXM3o5QQ==
kind: Secret
metadata:
  name: secret
  namespace: prod
type: Opaque
