apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::933060838752:role/worker-yolov-role
automountServiceAccountToken: true