hpa:
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 70
  memoryUtilization: "800Mi"

image: "933060838752.dkr.ecr.us-east-1.amazonaws.com/yolov5-mf-dev"
tag: ""

deployment:
  strategy:
    maxSurge: 1
    maxUnavailable: 0
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 1000Mi