apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name }}-bot-ingress
  namespace: {{ .Release.Namespace }}
  {{- if empty .Values.ingress.annotaions }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: mf.atech-bot.click
    external-dns.alpha.kubernetes.io/alias: "true"
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: "my-ingress-group"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-1:933060838752:certificate/c9d30fb0-5a6a-447c-a859-6107cfa564f6"
  {{- else }}
  {{- with .Values.ingress.annotations }}
  annotations: |-
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "alb" }}
  rules:
  - host: mf.atech-bot.click
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: originalbotservice
            port:
              number: 5000