apiVersion: v1
kind: ServiceAccount
metadata:
  name: bot-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::933060838752:role/mf-bot-role
automountServiceAccountToken: {{ .Values.automountServiceAccountToken | default "true" }}