kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  namespace: {{ .Release.Namespace }}
data:
  appUrl: "https://mfdev.atech-bot.click"
  serverEndpoint: "https://mfdev.atech-bot.click/sns_update"